[metadata.colnames]
sample_id = "Experiment_Name"
donor_id = "DonorID"
modality = "Library_Type"
chip_well = "Chip_Well"
index_plate = "Index_Plate"
well = "Well"

[references]
RNA = "x"
ADT = "y"
VDJ = "z"
ATAC = "/cellranger-ref/refdata-cellranger-arc-mm10-2020-A-2.0.0"
