[core]
sample_pattern="(^[^_]+)[_]"
ref="/home/amsesk/super1/cdiff_evo/ref/GCF_021378415.1_ASM2137841v1_genomic.fna"


[vcf_filter]
mqrs_min = -2.0
dp_min = 10

[opts]
remove_intermediate_bams=true

[resources]
threads=8
memory=24


