# This workflow will install Python dependencies, run tests and lint with a single version of Python For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pmbi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install project
        run: |
          pip install -e .[test]
      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run tests
        run: pytest -s -vvvv -l --tb=long
      - name: Generate coverage report
        run: |
          pytest --cov .
          cp .coverage ../

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
